### ISSUE TITLE
CAMBIO DE NOMBRE EN APARTADO

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#10]
QUE TAL JOVENES, NECESITO QUE SE LE HAGA UN CAMBIO DE NOMBRE A UNA DE LAS OPCIONES EN EL APARTADO DE **DATOS DE DOMICILIO** EN EL FORMULARIO DE SOLICITUD, ESTE CAMBIO SERIA DE **NINGUNO** A **PROPIO** 
![Captura de pantalla 2024-09-05 114654](https://github.com/user-attachments/assets/31a9f34f-5ca4-43fc-a2df-016b5874a8cf)

**Comment by miguemi** [comment]
@ferxo27 buen dia, ya se hizo el cambio solicitado. Se encuentra en testing, enviaremos a producción y con eso estariamos cerrando el ticker
