### ISSUE TITLE
Contrato final para clientes 

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/Tickets#11]
Según lo hablado anterior mente este será el nuevo modelo de contrato para los clientes 
Gracias 

[CONTRATO PARA CLIENTES .docx](https://github.com/user-attachments/files/17282944/CONTRATO.PARA.CLIENTES.docx)
Se requiere que esta implementacion sea para el día de hoy ya que se necesita para poder empezar a dar créditos esta semana

**Comment by alanfzf** [comment]
Entendido, vamos a cerrar este ticket en favor del ticket #3 , que ya estaba abierto previamente y esta relacionado a la edicion del contrato de clientes.
