### ISSUE TITLE
Solicitudes [Reporte: datos de clientes]

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/Tickets#12]
Buenas tardes, por favor modificar la hoja que se genera de la solicitud de financiamiento, poner los datos en tabla, para que la información sea más clara al visualizarse, Gracias.

<img width="951" alt="Captura de pantalla 2024-10-09 a la(s) 2 28 39 p  m" src="https://github.com/user-attachments/assets/4a9f8822-3dda-4c7b-af96-624a79fecb5c">

**Comment by alanfzf** [comment]
Arreglado (https://github.com/Finanssoreal/api-finanssoreal/pull/58), solo se esta pendiente en subir los cambios al entorno de produccion

**Comment by miguemi** [comment]
Buenas tardes @lorenngarciaf asi quedaría el reportes de solicitud de finaciamiento, el cual pidió Edgar como requerimiento,
Agregar en cuadro los datos del cliente.....adjunto captura da pantalla para corroborar si todo esta bien, posterior enviar a producción .
![image](https://github.com/user-attachments/assets/1b308d99-3c9a-4aa2-9900-8dc8203d689a)
