### ISSUE TITLE
Solicitudes [Cuota mensual] 

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/Tickets#13]
Buena tarde, en el apartado de la respuesta de las solicitudes que ingresan al momento de calificar al cliente se le genera un interés respecto al nivel de riesgo que éste presente, por lo tanto a la clienta María Ester Méndez, se le ha otorgado un riesgo alto pero no sincroniza con la cuota ya que aparece en 0.00. Por favor verificar este error, gracias!!

<img width="1324" alt="Captura de pantalla 2024-10-09 a la(s) 2 33 24 p  m" src="https://github.com/user-attachments/assets/6a94b441-c8c1-4cd9-901c-c27f6599df46">

**Comment by alanfzf** [comment]
Temporalmente eliminamos, este campo del apartado de solicitudes ya que la cuota mensual se almacena dentro del financiamiento y por ende no se estaba calculando y era redundante, a futuro implementaremos nuevamente el apartado de cuota mensual en solicitudes, solo que obteniendo datos del financiamiento.
