### ISSUE TITLE
Solicitudes [Implementar edicion de comentario]

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/Tickets#14]
Buenas tardes, por favor agregar el botón para editar los comentarios en las respuestas a las solicitudes de financiamiento, para darle un seguimiento más eficiente a las solicitudes, Gracias. <img width="1324" alt="Captura de pantalla 2024-10-09 a la(s) 3 41 34 p m" src="https://github.com/user-attachments/assets/6086640f-3241-4f18-aa29-13d7364bef09">

**Comment by miguemi** [comment]
buen dia @lorenngarciaf , ya se encuentra el boton de edicion de comentario,  unicamente queda enviar a producción , y procedo a cerrar e ticket
![Screenshot 2024-10-11 at 9 52 34 AM](https://github.com/user-attachments/assets/5cd63ecd-9080-44d1-b117-7a5dc15082e5)
