### ISSUE TITLE
[Pagos] Errores en los estados de cuenta y calendario de cobros

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#16]
Buena tarde, en el archivo excel se adjuntan los errores que se han encontrado en los estados de cuentas de los clientes, así como las personas que aparecen con otro estado diferente al que se encuentran en el calendario. Por favor verificar para no afectar los récords. Gracias 
[Clientes revisar.xlsx](https://github.com/user-attachments/files/17332887/Clientes.revisar.xlsx)

**Comment by alanfzf** [comment]
Por favor volver a revisar el sistema se han enviado cambios al apartado de generacion de estados de cuenta, para cliente individual
