### ISSUE TITLE
Pruebas de solicitudes 

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#17]
Por favor eliminar las solicitudes de prueba para no tener confusiones. Gracias
<img width="1174" alt="Captura de pantalla 2024-10-10 a la(s) 3 15 57 p  m" src="https://github.com/user-attachments/assets/c8420266-02af-46a9-8974-064cdcf186e0">

**Comment by miguemi** [comment]
Buen dia @lorenngarciaf , ustedes pueden eliminar o finalizar los financiamientos que son de prueba, de esta manera:
Seguir, los pasos que estan la caputara de pantalla.

En este momento lo hare.

![Screenshot 2024-10-16 at 12 30 56 PM](https://github.com/user-attachments/assets/44e1ae21-1386-429c-bcca-3a8c718fafd7)
![Screenshot 2024-10-16 at 12 32 55 PM](https://github.com/user-attachments/assets/3b37a517-ee39-4d09-8d31-8a35844ff0e0)
