### ISSUE TITLE
Apartado para cambio de contraseña de usuario 

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#18]
se solicita un apartado para poder crear nuevas contraseñas a los usuarios en el apartado de usuarios

![Captura de pantalla 2024-10-10 105325](https://github.com/user-attachments/assets/db649bf8-9ca1-49ab-8bef-5c8d090ec8aa)

**Comment by alanfzf** [comment]
Ya se encuentra implemntado en control, gracias por el ticket
