### ISSUE TITLE
Editar [Agencias-Usuarios]

### ISSUE THREAD

**Issue by alanfzf** [Finanssoreal/Tickets#19]
Se requiere lo siguiente:
- [X] Permitir crear agencia sin RTU.
- [X] Buscar en usuarios por correo electronico.
- [X] Implementar la eliminacion pasiva (Desactivar unicamente los records, pero mantenerlos en la base de datos)

**Comment by alanfzf** [comment]
Que tal @ferxo27, @danilonino, ya se implemento, el campo requerido, para RTU y se implemento la busqueda por correo electronico, asi mismo se implemento la eliminacion pasiva de agencias, solo seria de confirmar en testing para poder enviar a produccion (https://github.com/Finanssoreal/api-finanssoreal/pull/63)

**Comment by danilonino** [comment]
Muchas gracias! Haremos las pruebas y le informaré gracias
