### ISSUE TITLE
ERROR EN EL AREA DE VIATICOS 

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#2]
TODAS LAS CASILLAS FUNCIONAN BIEN, EL ERROR LO DA A LA HORA DE ENVIAR LA SOLICITUD.
![Captura de pantalla 2024-10-01 102905](https://github.com/user-attachments/assets/7755df67-27d6-477c-a681-8187ad78eb10)

**Comment by miguemi** [comment]
Muy bien, vamos a revisar @ferxo27

**Comment by miguemi** [comment]
Se enviara a testing, una vez se cofirme su funcionamiento en testing se procederá a desplegar a producción 
https://github.com/Finanssoreal/api-finanssoreal/pull/51
