### ISSUE TITLE
Peticion de datos [Agencia]

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/Tickets#21]
NUMERO DE CELL
# DE CUENTA DE BANCO 
NOMBRE DEL BANCO 
NOMBRE DE LA CUENTA
TIPO DE CUENTA ( AHORRO O MONETARIA)
RTU O PATENTE 
DIRECCION EXACTA DE LA AGENCIA
FOTOGRAFIA DE PERFIL

**Comment by alanfzf** [comment]
Este requerimiento ya fue implementado sera enviado el dia de hoy (15/10/2024) a produccion a las 12:00 horas.

![imagen](https://github.com/user-attachments/assets/5910a2ba-ed14-4591-80dd-17682032df15)
