### ISSUE TITLE
Formulario de agencia

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/Tickets#22]
SI AL HACER UNA SOLICITUD DESDE AGENCIA, SI EL ASESOR NO LLENA ALGUN CAMPO OBLIGATORIO DENTIFICADO CON * NO DEBE DEJAR SEGUIR AL ASESOR HASTA QUE LOS CAMPOS OBLIGATORIOS ESTEN COMPLETOS

**Comment by alanfzf** [comment]
Completado
