### ISSUE TITLE
[Solicitudes] Correos electronicos

### ISSUE THREAD

**Issue by alanfzf** [Finanssoreal/tickets#23]
Arreglar las notificaciones

- [X] Al crear nueva solicitud  (se envia administradores).
- [x] Solicitud Aprobada (se envia agencias) cargar datos del vehiculo.
- [X] Solicitud Rechazada (se envia agencias)
- [X] Envio de usuario y bienvenida al cliente (creación de usuario y bienvenida)
- [x] Agencia al cargar los datos del vehículo notificar [master, administrador]
- [x] Al generar contrato [notificar, agencia] y enviar archivos (resolucion vehicular, proyeccion de pagos y datos de cobranza)
- [x] Fotografias del cliente (Cargarlas), se envia 45 minutos despues del email anterior.

**Comment by miguemi** [comment]
Se adjunta un diagama del flujo
![flujo de correos drawio](https://github.com/user-attachments/assets/40ad00d7-5c81-4284-9941-767324b7ae25)


https://drive.google.com/file/d/1ZC6_Jz40ntUXSkyFqxElbBIgSHclsRSa/view?usp=sharing

**Comment by alanfzf** [comment]
# Detalle de los emails 

## Email 1
- titulo: Nueva solicitud
- contenido: ¡Se ha recepcionado una nueva solicitud de financiamiento!, botones, redireccion area de solicitudes
- emisores: agencia
- receptores: administracion y analisis

## Email 2
- titulo: Financiamiento aprobado
- contenido: El financiamiento ha sido aprobado, se solicita cargar datos del vehiculo y adjuntar fotografias de la nota del vehiculo.
- emisores: Analisis
- receptores:  Agencias

## Email 3
- titulo: Datos del vehiculo
- contenido: Los datos del vehiculo han sido cargados
- emisores: Agencia
- receptores: Analisis

## Email 4
- titulo: Contrato activado
- contenido: El contrato de financiamiento ha sido activado
- emisores: analisis
- receptores: agencia
- archivos: resolucion vehicular, proyeccion de pagos y datos de cobranza

## Email 5
- titulo: Fotografias de cliente
- contenido: Cargar las fotografias correspondientes que el sistema solicita
- emisores: analisis
- receptores: agencia
- retraso: 45 minutos (al  mismo tiempo que email 4, retraso 45 minutos)

**Comment by alanfzf** [comment]
Completado se procede a cerrar el ticket
