### ISSUE TITLE
Creacion de usuario [Mejorar manejo de errores]

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/tickets#24]
A la hora de crear un usuario me aparece una ventana con un error
![Captura de pantalla 2024-10-12 082405](https://github.com/user-attachments/assets/09de7a12-d9bd-4e42-8310-65c30dc77cae)

**Comment by alanfzf** [comment]
Vamos a reformular este ticket, parece que lo necesario, seria implementar mas mensajes de errores con respecto a por que no se ha podido crear el cliente:
- El correo electronico ya existe en la base de datos
- Las verificacion de contrasenias no coincide.
