### ISSUE TITLE
[Seguros] Formatos automaticos

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/tickets#27]
# Formatos automaticos

Se adjuntarion los tickets relacionados a la aseguradora

## REALIZAR FORMATOS AUTOMATICOS PARA ASEGURADORA GENERAL #27
[1. ASR-32 - EDITABLE - v2024.pdf](https://github.com/user-attachments/files/17385425/1.ASR-32.-.EDITABLE.-.v2024.pdf)
EN ESTE DOCUMENTO SE SOLICITA EL LLENADO DE TODOS LOS CAMPOS QUE LA PARTE ADMINISTRATIVA INDIQUE LOS CUALES LLEVARAN DATOS DE LA EMPRESA Y REPRESENTANTE LEGAL 

## CONSENTIMIENTO IDIVIDUAL DEL CLIENTE #28
[Consentimiento Individual de seguro colectivo de vida para Saldo deudor.pdf](https://github.com/user-attachments/files/17385439/Consentimiento.Individual.de.seguro.colectivo.de.vida.para.Saldo.deudor.pdf)
EN ESTE DOCUMENTO SE TIENE QUE RELLENAR ALGUNOS CAMBIOS DE FORMA AUTOMATICA Y OTROS DEBERAN QUEDAR A LA DISCRECION DE LA ADMINISTRACION, ADMINISTRACION DEBERA DETERMINAR QUE CAMPOS SERAN RELLENADO AUTOMATICAMENTE Y CUALES QUEDARAN A DISCRECION.

## SALDOS DEUDORES #29
[Solicitud de saldos deudores .pdf](https://github.com/user-attachments/files/17385494/Solicitud.de.saldos.deudores.pdf)
EN ESTE DOCUMENTO DEBERAN IR DATOS DEL FINANCIAMIENTO CANTIDAD FINANCIADA Y DATOS DE LA EMPRESA COMO RESPONSABLE DEL SEGURO, ESTE DOCUMENTO Y TODOS LOS ANTERIORES SE SOLICITARAN A ADMINISTRACION PARA QUE ELLOS DEN EL MODELO A SEGUIR 

## REPORTE DE ESTADO DE CLIENTES Y DEUDA PARA ASEGURADORA #30
[REPORTE MENSUAL.xlsx](https://github.com/user-attachments/files/17386268/REPORTE.MENSUAL.xlsx)
TODOS ESTOS CAMPOS SE TIENEN QUE RELLENAR DE FORMA AUTOMATICA Y SE TENDRA QUE ENVIAR CADA 1RO DE CADA MES AL CORREO QUE INDIQUE LA ASEGURADORA (EL CUAL LES PROPORCINARE YO) EN LOS DOCUMENTOS SE INDICAN LOS DATOS QUE SE SOLICITAN, CONCIDERO QUE TODOS ESOS DATOS EL SISTEMA LOS TIENE

**Comment by miguemi** [comment]
@danilonino aqui adjuntamos los avances, saludos
https://youtu.be/7EOOV-f9EJE

**Comment by miguemi** [comment]
Buenas tardes aqui adjunto los documentos pdf con formulario implementado de los tres documentos del seguro

[asr-32.pdf](https://github.com/user-attachments/files/17548334/asr-32.pdf)
[saldoDeudores.pdf](https://github.com/user-attachments/files/17548335/saldoDeudores.pdf)
[saldoDeudorIndividual.pdf](https://github.com/user-attachments/files/17548336/saldoDeudorIndividual.pdf)

**Comment by flying-digital** [comment]
[SaldoDeudorIndividual.pdf](https://github.com/user-attachments/files/17559424/SaldoDeudorIndividual.pdf)

**Comment by miguemi** [comment]
Reportes  de seguro, rellenados por administración 
[asr-32.pdf](https://github.com/user-attachments/files/17589157/asr-32.pdf)
[saldoDeudores .pdf](https://github.com/user-attachments/files/17589160/saldoDeudores.pdf)

**Comment by lorenngarciaf** [comment]
[REPORTE INICIAL.xlsx](https://github.com/user-attachments/files/17651212/REPORTE.INICIAL.xlsx)

**Comment by lorenngarciaf** [comment]
[ROSA ELENA COC CUC.pdf](https://github.com/user-attachments/files/17651217/ROSA.ELENA.COC.CUC.pdf)
[CESAR OCTAVIO MONROY FELIPE.pdf](https://github.com/user-attachments/files/17651218/CESAR.OCTAVIO.MONROY.FELIPE.pdf)
[MAIRON REVOLORIO Y REVOLORIO.pdf](https://github.com/user-attachments/files/17651219/MAIRON.REVOLORIO.Y.REVOLORIO.pdf)
[ALBINO DIAZ CANTORAL.pdf](https://github.com/user-attachments/files/17651220/ALBINO.DIAZ.CANTORAL.pdf)
[CALIXTO JAVIER TIUL TEYUL.pdf](https://github.com/user-attachments/files/17651221/CALIXTO.JAVIER.TIUL.TEYUL.pdf)
[MARTA POP BAC.pdf](https://github.com/user-attachments/files/17651222/MARTA.POP.BAC.pdf)
[HERMELINDO CUC CAC.pdf](https://github.com/user-attachments/files/17651223/HERMELINDO.CUC.CAC.pdf)
[CARLOS RUBEN GUTIERREZ SANDOVAL.pdf](https://github.com/user-attachments/files/17651224/CARLOS.RUBEN.GUTIERREZ.SANDOVAL.pdf)

**Comment by miguemi** [comment]
https://youtu.be/dU_0aVdtrhA
@danilonino  buenas tardes, aqui un video para lo de seguros (reporte en excel)
