### ISSUE TITLE
CONSENTIMIENTO IDIVIDUAL DEL CLIENTE 

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/tickets#28]
[Consentimiento Individual de seguro colectivo de vida para Saldo deudor.pdf](https://github.com/user-attachments/files/17385439/Consentimiento.Individual.de.seguro.colectivo.de.vida.para.Saldo.deudor.pdf)
EN ESTE DOCUMENTO SE TIENE QUE RELLENAR ALGUNOS CAMBIOS DE FORMA AUTOMATICA Y OTROS DEBERAN QUEDAR A LA DISCRECION DE LA ADMINISTRACION, ADMINISTRACION DEBERA DETERMINAR QUE CAMPOS SERAN RELLENADO AUTOMATICAMENTE Y CUALES QUEDARAN A DISCRECION.

**Comment by miguemi** [comment]
Que tal, hemos estado avanzando, ya se logran llenar los documentos (PDF) automaticamente con los datos que se obtienen de la Api.
