### ISSUE TITLE
modificación en el contrato clientes

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#3]
modificación en la cantidad de amortizaciones (inciso b) del contrato redondear cantidades.
![Imagen de WhatsApp 2024-10-02 a las 12 19 05_fcaf6c31](https://github.com/user-attachments/assets/b1f7cb43-1fd2-4f6c-90ef-c7870b63bfbd)

**Comment by alanfzf** [comment]
Finalizado, el nuevo disenio del contrato, unicamente faltaria enviar a produccion
