### ISSUE TITLE
Arreglos finales [usuarios-agencias]

### ISSUE THREAD

**Issue by alanfzf** [Finanssoreal/tickets#31]
Tareas: 
- [x] Eliminar los siguientes campos del formulario de agencias (modo administrador)
![image](https://github.com/user-attachments/assets/f7ef5f4e-bc33-42f1-afa3-e3c45a378d8f)
- [x] En agencias cuando no estan llenos los datos hacer que no permita enviar el formulario (si falta patente/rtu) `input de tipo archivo`
- [x] En el apartado de usuarios, botón editar informacion, agregar los campos de `phone` y `email`
![{08F756B2-B666-4ACA-9CFB-9B153E5A8CEB}](https://github.com/user-attachments/assets/a95fef3b-a973-4935-943f-8b40d530e1cd)

**Comment by miguemi** [comment]
Buen dia @alanfzf , ya se enviaron los cambios, solcitados, adjunto captura de pantalla .
![image](https://github.com/user-attachments/assets/a8ec1230-2862-460f-97c5-a104f1cd5452)
