### ISSUE TITLE
Contrato

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#34]
Buena tarde, al descargar el contrato en el espacio para la firma del representante legal, no queda el espacio adecuado para colocar su firma. (No sucede en todos los casos, pero supongo que es porque la ampliación de datos con cada cliente es distinta) por favor verificar ese problema. 
![contrato](https://github.com/user-attachments/assets/8e4120e5-ac5d-4fb4-80a3-7249edf34fc6)

**Comment by alanfzf** [comment]
Gracias por el reporte @lorenngarciaf, ahora lo visualizamos

**Comment by miguemi** [comment]
Buen dia , ya se envió el cambio a testing,  en el transcurso de la tarde estaremos enviando cambios a producción.
![image](https://github.com/user-attachments/assets/9eac3ae4-9e61-496a-8912-42d28ddd5299)
