### ISSUE TITLE
[Solicitud] Estado de solicitudes no refleja la realidad

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/tickets#35]
EL SISITEMA NO REGISTRA LOS DOCUMENTOS QUE YA ESTAN CARGADOS.
![Captura de pantalla 2024-10-22 113512](https://github.com/user-attachments/assets/ae1cca3a-c681-4665-86d2-a5a12dd93a24)

**Comment by alanfzf** [comment]
Detalles extra, que constituye una solicitud como completada:

1. DPI y recibo de luz: Se recibe al llenar la solicitud.
2. Fotos del comprobante. Se recibe cuando la agencia llena los datos del vehiculo.
3. Fotos del cliente. 
4. Factura. Esto es a la hora de recibir la factura y el analista carga al sistema ***(ESTO AUN NO ESTA IMPLEMENTADO, no tomar en cuenta)***
5. Contrato: esto es a la hora de recibir el contrato en físico y escanearlo (administracion)

**Comment by miguemi** [comment]
buena tarde ya se corrigió  el error, en el transcurso de la tarde enviaremos a producción 
Esto fue una prueba
![image](https://github.com/user-attachments/assets/f24d98be-c88e-4e55-9a56-d2f81c668968)
