### ISSUE TITLE
[Pagos] Mal calculo de moras

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#36]
El sistema no le ha generado moras a algunos clientes a pesar de que han pagado en fechas fuera de su límite.
<img width="1324" alt="Captura de pantalla 2024-10-22 a la(s) 1 10 29 p  m" src="https://github.com/user-attachments/assets/ac445f20-81ee-4d43-b8a1-f6a901419ddb">
<img width="1363" alt="Captura de pantalla 2024-10-22 a la(s) 1 11 08 p  m" src="https://github.com/user-attachments/assets/1052e00c-2ac3-40f9-8a88-6780f48108fe">

**Comment by alanfzf** [comment]
Por favor volver a revisar el sistema se han enviado cambios al apartado de generacion de estados de cuenta, para cliente individual
