### ISSUE TITLE
Tasas de intéres

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#37]
Buen día verificar que esten correctos los intereses oficiales para otorgar financiamientos.
<img width="394" alt="Captura de pantalla 2024-10-23 a la(s) 9 52 04 a  m" src="https://github.com/user-attachments/assets/d5d793d0-d95e-4b29-8199-60fae8f3d47d">

**Comment by alanfzf** [comment]
Eso lo pueden, visualizar y editar, desde un rol master, en el siguiente apartado:

https://control.finanssoreal.com/intereses/administrar
