### ISSUE TITLE
REFINANCIAMIENTO REGISTRAR PAGO

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#38]
No me aparece la opción para agregar el pago del cliente Carlos Ruben Gutierrez Sandoval, al cual se le realizo un refinanciamiento con una cuota de Q1464, únicamente me aparece el apartado del anterior crédito.

<img width="1233" alt="Captura de pantalla 2024-10-23 a la(s) 10 48 53 a  m" src="https://github.com/user-attachments/assets/25a4f4d7-bb5b-4e2a-b681-16ff28e82e2c">

**Comment by miguemi** [comment]
![image](https://github.com/user-attachments/assets/29623605-f979-4c93-aa9d-7031e0b7bfef)

![image](https://github.com/user-attachments/assets/35ecb234-f2c4-49b6-afc3-acd8e2bc0523)

**Comment by alanfzf** [comment]
Se han enviado los cambios necesarios, para arreglar este error, procedemos a cerrar el ticket
