### ISSUE TITLE
datos de cobranza vehicular 

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/Tickets#4]
se solicita cambios en el documento de datos de cobranza vehicular, se requiren los siguientes cambios.
En caso de incumplimiento de la cuota por dos meses consecutivos se procederá a reportar el vehículo como robado y se interpondrá una denuncia en contra del cliente.

	En caso de devolución del vehículo, el cliente deberá cancelar el 40% de depreciación sobre el valor inicial del mismo, este pago es obligatorio e indispensable de lo contrario no se recibirá el vehículo.

	Las visitas de cobranza tienen un costo adicional que dependerá de la distancia en kilómetros de ubicación entre las oficinas de Finanssoreal y el cliente.

	Finanssoreal S.A. no es responsable de las garantías del vehículo, el cliente deberá avocarse directamente con los distribuidores de la marca.

	Finanssoreal S.A. no es responsable de multas administrativas, tributarias y penales en las que el cliente incurra cuando se encuentre en el uso del vehículo.

	Al finalizar el pago total del financiamiento se procederá a realizar el traspaso del vehículo a nombre del cliente por lo que tendrá el plazo máximo de 60 días para efectuarlo. (En caso de incumplimiento, Finanssoreal S.A. se reserva el derecho de desactivar el vehículo).

INFORMACIÓN DE PAGO

Los pagos deberán realizarse al número de cuenta 6500004830 (Banco Industrial) a nombre de Finanssoreal y reportar el comprobante de pago al contacto 5001-3354.

Cualquier consulta relacionada a su estado de cuenta comunicarse al 5001-3354 o bien escríbanos al correo institucional finanssoreal@gmail.com 

ESTOS DATOS SE SOLICITAN AGREGAR EN LA PARTE INFERIOR DEL DOCUMENTO YA ESABLECIDO ELIMINANDO EL PARAFO DE NOTA: SIENDO REMPLAZADO POR LA INFORMACION ANTERIOR ENVIADA. GRACIAS

**Comment by miguemi** [comment]
Aqui adjunto el documento de datos de cobranza vehicular modificado.
Quedo a la espera de cualquier cambio a realizar, de lo contrario se envia a testing y posterior a producción.
@danilonino 
[download.pdf](https://github.com/user-attachments/files/17236441/download.pdf)

**Comment by miguemi** [comment]
Buen dia @danilonino  aqui adjunto el formato final de documento de datos cobranza vehicular.
Quedo a la espera de cualquier cambio a realizar, de lo contrario se envia a testing y posterior a producción.
[download.pdf](https://github.com/user-attachments/files/17246629/download.pdf)

**Comment by danilonino** [comment]
Muchas gracias! Concidero que así quedo mejor!

**Comment by alanfzf** [comment]
Cambios aprobados en testing https://github.com/Finanssoreal/api-finanssoreal/pull/52 quedamos pendientes de que visualicen los cambios en https://testing.finanssoreal.com, una vez todo este correcto procedemos a cerrar el ticket

**Comment by miguemi** [comment]
buena tarde @danilonino  el nuevo formato ya se encuentra en produccion,  con eso se cierra el ticket.
Saldudos
