### ISSUE TITLE
[Calculadora] fallo en calculos

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#45]
Buenos días, por favor verifique por qué al momento de cotizar un mototaxi no se genera el calculo, unicamente con la opción de moto se puede
<img width="1177" alt="Captura de pantalla 2024-10-31 a la(s) 10 16 41 a  m" src="https://github.com/user-attachments/assets/3bd0a6f3-7278-4596-88d3-b743b286b92a">

**Comment by alanfzf** [comment]
Gracias ahora visualizamos.

**Comment by alanfzf** [comment]
Se han enviado los arreglos respectivos, para el cotizador.

![imagen](https://github.com/user-attachments/assets/836dfdec-158d-4730-807f-521420070010)
