### ISSUE TITLE
[Pagos] Busqueda de clientes

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#46]
Buenos días, hoy que quería agregar el pago de la nueva clienta MARIA ESTER MENDEZ RUIZ, inicialmente su financiamiento me aparecía en la "perdidas" lo agregue a vigentes y después que intento buscar su nombre en pagos para cargar su boleta no me aparece la clienta, ya intente de varias formas, por favor apoyarme para encontrarla. gracias <img width="1177" alt="Captura de pantalla 2024-11-02 a la(s) 11 53 57 a m" src="https://github.com/user-attachments/assets/d1a2c363-d1fd-4e5b-b842-241d16fbfdb3">

**Comment by alanfzf** [comment]
![imagen](https://github.com/user-attachments/assets/724ce1f9-e2a2-4435-a402-82425336e3e1)

Listo se ha solucionado el error, en unos momentos subiremos los cambios respectivos.
