### ISSUE TITLE
[Financiamientos] Documentos

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#49]
En algunas ocasiones al consultar el dpi, solicitud u otros documentos, cuando ingreso a un cliente me salen los datos de otros, normalmente los clientes más recientes son los que salen.

**Comment by alanfzf** [comment]
Gracias por el reporte, lo estaremos revisando.

**Comment by alanfzf** [comment]
Se han enviado algunos cambios, por favor nos comenta, si este error vuelve a suceder, para que podamos, verificar, procederé a cerrar el ticket de momento.
