### ISSUE TITLE
ERROR DE CONTRATO 

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#5]
EN LA PAGINA 1 DEL CONTRATO FALTAN LOS DATOS DE MUNICIPIO Y DEPARTAMENTO
![Captura de pantalla 2024-10-02 143935](https://github.com/user-attachments/assets/96f4c3c9-6bb8-4fc2-a26e-5a15d44d48cb)

**Comment by miguemi** [comment]
Buen dia @ferxo27 el error  se presentó, por haber creado una agencia sin un minicipio. Ya fue corregido agrego evidencias
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/81137a41-30ae-4415-a19a-f1c3b3a4f3c4">
y procedemos a cerrar el ticket.
saludos

**Comment by ferxo27** [comment]
ENTERADO MUCHAS GRACIAS
