### ISSUE TITLE
[Error]: Suma de amortización y capital

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#57]
### Descripción del problema

Al cliente Roberto Carlos Mo Rivera, en sus datos de financiación la suma de amortización y capital da un total de 852, su cuota es de 851, por favor editar para que la suma de ambos de el total de 851.

### Pasos para reproducir

```markdown
1.
2.
3.
4.
```

**Comment by alanfzf** [comment]
Buen, dia se ha ajustado el valor del interes mensual de 389 a 388, para compensar por el valor erroneo almacenado en la base de datos
