### ISSUE TITLE
[Feature]: Comentarios financiamientos

### ISSUE THREAD

**Issue by alanfzf** [Finanssoreal/tickets#58]
### Tipo de implementación

Implementación de una nueva funcionalidad

### Descripción de la nueva característica

Implementar una funcion para agregar comentarios generales a un financiamiento

### Justificación

Es necesario, ya que debido a cualquier error, en el sistema o cualquier anotacion relevante a un financiamiento no se cuenta con un apartado para alojar un comentario o anotacion

**Comment by Romeoteni188** [comment]
Listo ya se agrego el nuevo campo de comentario en modulo de financiamiento.
