### ISSUE TITLE
ERROR AL SOLICITAR CAMBIO DE CONTRASEÑA 

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#6]
ADJUNTO UN VIDEO EN DONDE SE MUESTRA EL ERROR QUE GENERA A LA HORA DE SOLICITAR EL CAMBIO DE CONTRASEÑA.

https://github.com/user-attachments/assets/07330363-f960-4b01-bb00-08301b4c24cc

**Comment by alanfzf** [comment]
Debido a que el correo de restablecimiento de contrasenia fue enviado hace 4 horas, ya no es valido, si prueba nuevamente, con una solicitud reciente, el restablecimiento de clave funciona
