### ISSUE TITLE
[Error]:Meses de financiamiento

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#60]
### Descripción del problema

por favor Revisar por qué no termina el financiamiento el 30 de junio, ya que según los cálculos solo le esta reflejando 17 meses <img width="1021" alt="Captura de pantalla 2024-12-02 a la(s) 10 40 31 a m" src="https://github.com/user-attachments/assets/9e60aca1-6afc-443e-9b1b-54ac1a061dee">

### Pasos para reproducir

```markdown
.
```

**Comment by miguemi** [comment]
Esta resuelto el bug en la fecha, adjunto captura, para que pueda revisar @lorenngarciaf 
![image](https://github.com/user-attachments/assets/3e6c1728-1a62-45ec-baf6-d3db0ab748e4)

**Comment by alanfzf** [comment]
NOTA: En base al requerimiento solicitado la fecha final sera calculada en base a la `primer fecha de pago`, por lo tanto debemos de tener en cuenta el siguiente calculo:

$$
\text{FechaInicial} = \text{2025-01-01}
$$

$$
\text{Meses} = \text{18}
$$

$$
\text{FechaFinal} = \text{FechaInicial} + (\text{Meses} - 1)
$$

$$
\text{FechaFinal} = \text{2026-06-01}
$$
