### ISSUE TITLE
Cotizador calculadora

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#61]
### Tipo de implementación

Mejora de una función existente

### Descripción de la nueva característica

En la calculadora para usuarios de agencias, no permitir que puedan variar de intere
![PHOTO-2024-12-04-10-14-46](https://github.com/user-attachments/assets/e745b3fd-93ec-4f5f-bf6f-390bd578343b)
ses. Dejarlo únicamente con el 3%.

### Justificación

Que el analista y asesor de agencias tengan el control para cambiar de interés y trasladar esa información a los usuarios de agencias

**Comment by miguemi** [comment]
![image](https://github.com/user-attachments/assets/dc1ef67e-15c0-4686-ae45-26ea19340a64)
