### ISSUE TITLE
[Feature]: eliminacion visual de gastos administrativos en calculadora de agencias 

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/tickets#62]
### Tipo de implementación

Mejora de una función existente

### Descripción de la nueva característica

En la parte de calculadora de agencias aparece en cobro de gastos administrativos que se le realizan al cliente esto debe de ser eliminado únicamente visualmente, ya que el cobro se debe seguir realizando de la forma en que actualmente se hace. Al realizar este cambio se deberá también cambiar el gasto administrativo de 2,400 a 2,800 

### Justificación

Esto está generando conflicto con varias agencias y al hablar con los gerentes de algunas marcas hicieron la sugerencia de ocultar esa información ya que provoca celo en los asesores y buscan querer pedir más comisión de la que se les está dando

**Comment by alanfzf** [comment]
NOTA: se han cambiado los GAT, para motos a los siguientes valores:

'CARRO'    => 5700,
'MOTO'     => 2800,
'MOTOTAXI' => 3800,
'HIPOTECA' => 7500,
