### ISSUE TITLE
[Error]: Mezcla de información

### ISSUE THREAD

**Issue by lorenngarciaf** [Finanssoreal/tickets#63]
### Descripción del problema

Los clientes: Brandon Geovany Constancia Sop y Victor Domingo Cuz Sacul tenían los datos iguales en los detalles del vehículo, incluyéndo la factura y demás documentos.

### Pasos para reproducir

```markdown
.
```

**Comment by alanfzf** [comment]
Buen dia no hemos logrado reproducir el error, en caso de que ocurra nuevamente, por favor abrir un nuevo ticket gracias
