### ISSUE TITLE
Reportes [Autorizacion de credito]

### ISSUE THREAD

**Issue by danilonino** [Finanssoreal/Tickets#8]
MOTOR
COLOR
TIPO
CHASIS VIN Y SERIE
MARCA 
MODELO
LINEA
FECHA 
NOMBRE DE AGENCIA (LA AGENCIA QUE REALIZO LA SOLICITUD)

**Comment by danilonino** [comment]
PARA LAS MOTOCICLETAS DE MARCA BAJAJ EL DOCUMENTO DE DESEMBOSO SE TIENE QUE ENVIAR AL SIGUIENTE CORREO 
TAMBIEN SE TIENE QUE ENVIAR A LOS CORREOS DE LAS AGENCIAS 
VALIDACIONESCREDITOSYCOBROS@GRUPOUMA.COM

**Comment by ferxo27** [comment]
SOLICITO AGREGAR LA FIRMA DE EL DOCUMENTO  1 AL DOCUMENTO 2
DOCUMENTO #1
![Imagen de WhatsApp 2024-10-04 a las 12 05 37_9526edca](https://github.com/user-attachments/assets/d42b3159-bdaf-4dc4-bc23-30b68f23e66a)

DOCUMENTO #2 

![Captura de pantalla 2024-10-04 121145](https://github.com/user-attachments/assets/14e73cf4-274b-4c42-9296-d770090372d3)

**Comment by miguemi** [comment]
Agregar cambios a reporte de resolucion
![image](https://github.com/user-attachments/assets/5dc777de-69d3-4e00-aa3e-d33601e4aacb)

**Comment by miguemi** [comment]
Buen dia, ya envie los cambios solicitados. Solo queda probar en testing, posterior enviar a producción 
![image](https://github.com/user-attachments/assets/3511d1c5-308f-4faf-828e-cab27960d809)

**Comment by miguemi** [comment]
Buen dia @danilonino , @ferxo27  procedemos a cerrar el ticket ya se encuentra en testing, solo falta enviar a producción.
