### ISSUE TITLE
CAMBIO DE LOGISTICA Y CONTRATO

### ISSUE THREAD

**Issue by ferxo27** [Finanssoreal/Tickets#9]
Solicito un cambio de lugar del botón de editar datos del vehículo, esto para facilitar la gestión y así poder tener a la vista ese proceso.
el cambio es del apartado de contratos al apartado de solicitudes.

![1](https://github.com/user-attachments/assets/34d5d0fb-afa2-4608-87cd-84d607d2e9a3)
![2](https://github.com/user-attachments/assets/8bf24d69-6c52-498e-ba43-62855bb84824)

**Comment by miguemi** [comment]
Buen dia @ferxo27  se ha tomando el ticket, estare reportando cambios salu2

**Comment by miguemi** [comment]
@ferxo27 buen dia, ya enviamos los cambios a testing, si no hay algo que modificar, estariamos enviando a producción y al mismo tiempo cerrar el ticker.

**Comment by alanfzf** [comment]
Cerraramos este ticket, solo unicamente necesitamos enviar a produccion
